env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  eqeqeq:
    - error
    - always
  semi:
    - error
    - always
  quotes:
    - error
    - single

